name: Update Visualizations

on:
  schedule:
    # Runs every 6 hours (adjust cron schedule as needed)
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  update-visualizations:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Replace with the version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install plotly

    - name: Run Python scripts
      run: |
        python bubble_sort_plotly.py
        python selection_sort_plotly.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add static/visualizations/*.html
        git commit -m "Updated visualizations via GitHub Actions" || echo "No changes to commit"
        git push
